// load News 
export const LOAD_PRODUCTS_START = "LOAD_PRODUCTS_START";
export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS_SUCCESS";
export const LOAD_PRODUCTS_FAIL = "LOAD_PRODUCTS_FAIL";


// Message/Error
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";

export const REMOVE_EXISTING_ERRORS = "REMOVE_EXISTING_ERRORS";


//Load perticular News 
export const LOAD_PARTICULAR_PRODUCTS_START = "LOAD_PARTICULAR_PRODUCTS_START";
export const LOAD_PARTICULAR_PRODUCTS_SUCCESS = "LOAD_PARTICULAR_PRODUCTS_SUCCESS";
export const LOAD_PARTICULAR_PRODUCTS_FAIL = "LOAD_PARTICULAR_PRODUCTS_FAIL";


export const LOAD_SEARCH_START = "LOAD_SEARCH_START";
export const LOAD_SEARCH_SUCCESS = "LOAD_SEARCH_SUCCESS";
export const LOAD_SEARCH_FAIL = "LOAD_SEARCH_FAIL";


export const ADD_PRODUCT_TO_CART_START = "ADD_PRODUCT_TO_CART_START";
export const ADD_PRODUCT_TO_CART_SUCCESS = "ADD_PRODUCT_TO_CART_SUCCESS";
export const ADD_PRODUCT_TO_CART_FAIL = "ADD_PRODUCT_TO_CART_FAIL";


export const REMOVE_PRODUCT_FROM_CART_START = "REMOVE_PRODUCT_FROM_CART_START";
export const REMOVE_PRODUCT_FROM_CART_SUCCESS = "REMOVE_PRODUCT_FROM_CART_SUCCESS";

export const REMOVE_CART_ITEMS_ON_SUCCESS = "REMOVE_CART_ITEMS_ON_SUCCESS";

export const SAVE_FILTER_OPTIONS = "SAVE_FILTER_OPTIONS";
